## Main broQue Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broque
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: broque-server
subjects:
  - kind: ServiceAccount
    name: broque
    namespace: default
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broque-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Main broQue application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broque-deployment
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: broque
  template:
    metadata:
      labels:
        app: broque
    spec:
      serviceAccount: broque
      containers:
        # Put PG container first in case there is any ordering imposed by K8s/kubelet
        - name: postgres
          image: postgres
          volumeMounts:
            - name: broque-data-volume
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: localpass
            - name: PGDATA
              value: /data/pgdata      
        - name: broque
          image: johnnyb61820/broque:0.0.9
          ports:
            - containerPort: 3000
          env:
            - name: DB_PASS
              value: localpass
          startupProbe:
            tcpSocket: 
              port: 3000
            periodSeconds: 60
      volumes:
        - name: broque-data-volume
          persistentVolumeClaim:
            claimName: broque-data
---
apiVersion: v1
kind: Service
metadata:
  name: broque
spec:
  selector:
    app: broque
  ports:
    - targetPort: 3000  
      port: 80
---
## broQue Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broque-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broque-operator
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broque-operator
subjects:
  - kind: ServiceAccount
    name: broque-operator
roleRef:
  kind: Role
  name: broque-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broque-operator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broque-operator
  template:
    metadata:
      labels:
        app: broque-operator
    spec:
      serviceAccount: broque-operator
      containers:
        - name: broque-operator
          image: johnnyb61820/broque:0.0.9
          args: 
            - operator
